[package]
name = "probe-rs-rtt-runner"
version = "0.1.0"
authors = ["Eike Siewertsen <eike@allv.is>"]
edition = "2018"

[dependencies]
probe-rs = "0.9.0"
probe-rs-rtt = "0.4.0"
env_logger = "0.7.1"
anyhow = "1.0.31"
log = "0.4.8"
structopt = "0.3.14"
ctrlc = "3.1.4"
goblin = "0.2.3"
